# Generated by Django 5.1.2 on 2026-03-07 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('member_created', 'Member Created'), ('member_updated', 'Member Updated'), ('member_deleted', 'Member Deleted'), ('member_checkin', 'Member Checked In'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('plan_created', 'Plan Created'), ('plan_updated', 'Plan Updated'), ('staff_added', 'Staff Added')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, help_text='Extra data related to the activity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
