# Generated by Django 5.1.2 on 2026-03-08 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('member_type', models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='memberpayment',
            options={'get_latest_by': 'expiration_date', 'ordering': ['-date_of_payment']},
        ),
        migrations.AddField(
            model_name='memberpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant_app.member'),
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
