# Generated by Django 5.1.2 on 2026-03-08 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0003_remove_subscriptionplan_created_at_and_more'),
        ('tenant_app', '0004_member_alter_memberpayment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gymbranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=20)),
                ('accent_color', models.CharField(default='#22c55e', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public_app.gym')),
            ],
        ),
    ]
