# Generated by Django 5.1.2 on 2026-03-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0003_remove_subscriptionplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='public_app.gym'),
        ),
    ]
